import { runStatusEmailIdempotencySelfChecks } from "@/lib/email/status-mail-idempotency-checks";
import { runStatusEmailConcurrencySelfChecks } from "@/lib/email/status-mail-concurrency-checks";
import { runTournamentHubEmailDesignChecks } from "@/lib/email/tournament-hub-email-checks";
import { runTeamDirectoryChecks } from "@/lib/team-directory/team-directory-checks";
import { runScheduleSelfChecks } from "./run-checks";
import { runApplicationWindowSelfChecks } from "@/lib/public-application-state";
import { runMeinTurnierplanSelfChecks } from "@/lib/mein-turnierplan";
import { runMeinTurnierplanImportSelfChecks } from "@/lib/mein-turnierplan-import";
import { runMeinTurnierplanNormalizeSelfChecks } from "@/lib/mein-turnierplan-normalize";
import { runMeinTurnierplanLiveRenderSelfChecks } from "@/lib/mein-turnierplan-live-render";
import { runMeinTurnierplanPublicSourceSelfChecks } from "@/lib/mein-turnierplan-public-source";
import { runMeinTurnierplanSyncSelfChecks } from "@/lib/mein-turnierplan-sync";
import { runMeinTurnierplanParticipantCountChecks } from "@/lib/mein-turnierplan-participants-checks";
import { runTournamentParticipantsListChecks } from "@/lib/tournament-participants-checks";
import { runTournamentParticipantLogoManagementChecks } from "@/lib/tournament-participant-logos-checks";
import { runLivePageSelfChecks } from "@/lib/live/live-page-checks";
import { runMatchCenterDesignChecks } from "@/lib/live/match-center-checks";
import {
  runLiveMatchLayoutChecks,
  runPublicTeamLabelChecks,
} from "@/lib/schedule/names-checks";
import { runTournamentStatusCapacityChecks } from "@/lib/tournament-status-checks";
import { runSiteUrlAndCspChecks } from "@/lib/site-checks";
import { runAuthLoginValidationChecks } from "@/lib/auth/auth-login-validation-checks";
import { runAuthCallbackChecks } from "@/lib/auth/auth-callback-checks";
import { runClubProfileSecurityChecks } from "@/lib/auth/club-profile-security-checks";
import { runDuplicateApplicationChecks } from "@/lib/applications/duplicate-application-checks";
import { runGuestApplicationFieldsChecks } from "@/lib/applications/guest-application-fields-checks";
import { runOptionalApplicationFieldsChecks } from "@/lib/applications/optional-application-fields-checks";
import { runCancellationRequestsChecks } from "@/lib/cancellations/cancellation-checks";
import { runCancellationEmailHotfixChecks } from "@/lib/cancellations/cancellation-email-hotfix-checks";
import { runTeamOperationsP2Checks } from "@/lib/team-operations-p2-checks";
import { runRbacChecks } from "@/lib/rbac/rbac-checks";
import { runRbacDomainRlsChecks } from "@/lib/rbac/rbac-domain-rls-checks";
import { runRbacSecurityDefinerChecks } from "@/lib/rbac/rbac-security-definer-checks";
import { runUserManagementChecks } from "@/lib/rbac/user-management-checks";
import { runInvitationChecks } from "@/lib/rbac/invitation-checks";
import { runInvitationAuthErrorChecks } from "@/lib/rbac/invitation-auth-errors-checks";
import { runInvitationServiceGrantsChecks } from "@/lib/rbac/invitation-service-grants-checks";
import {
  runInvitationAcceptanceChecks,
} from "@/lib/rbac/invitation-acceptance-checks";
import { runInvitationAcceptanceRpcChecks } from "@/lib/rbac/invitation-acceptance-rpc-checks";
import { runUserDeleteChecks } from "@/lib/rbac/user-delete-checks";
import { runPaymentStatusChecks } from "@/lib/payments/payment-checks";
import { runCommunicationChecks } from "@/lib/communications/communication-checks";
import { runCommunicationReceiptChecks } from "@/lib/communications/communication-receipt-checks";
import { runCommunicationRecipientPickerChecks } from "@/lib/communications/recipient-picker-checks";
import { runCommunicationRecipientDedupChecks } from "@/lib/communications/recipient-dedup-checks";
import { runCommunicationTeamDirectoryChecks } from "@/lib/communications/communication-team-directory-checks";
import { runCommunicationSendOutcomeChecks } from "@/lib/communications/communication-send-outcome-checks";
import { runCommunicationListChecks } from "@/lib/communications/communication-list-checks";
import { runCommunicationTableGrantChecks } from "@/lib/communications/communication-table-grant-checks";
import { runCommunicationInterruptedChecks } from "@/lib/communications/communication-interrupted-checks";
import { runHelpChatChecks } from "@/lib/help/help-chat-checks";
import { runApplicationCapacityDisplayChecks } from "@/lib/application-capacity-display-checks";
import { runPublicApplicationStatusDisplayChecks } from "@/lib/public-application-status-display-checks";
import { runPublicTournamentAnonVisibilityChecks } from "@/lib/tournaments/public-tournament-anon-visibility-checks";
import { runNewsSelfChecks } from "@/lib/news-checks";
import { runAdminScheduleParticipantChecks } from "@/lib/schedule/admin-schedule-participants-checks";
import {
  runMeinTurnierplanIdempotencyCheck,
  runMeinTurnierplanExistingManualGroupsCheck,
  runMeinTurnierplanManualOverrideCheck,
  runMeinTurnierplanSyncRpcSelfChecks,
  runMeinTurnierplanTransactionRollbackCheck,
} from "@/lib/mein-turnierplan-sync-rpc-checks";

try {
  const schedule = runScheduleSelfChecks();
  const applicationWindow = runApplicationWindowSelfChecks();
  const meinTurnierplan = runMeinTurnierplanSelfChecks();
  const meinTurnierplanImport = runMeinTurnierplanImportSelfChecks();
  const meinTurnierplanNormalize = runMeinTurnierplanNormalizeSelfChecks();
  const meinTurnierplanLiveRender = runMeinTurnierplanLiveRenderSelfChecks();
  const meinTurnierplanPublicSource = runMeinTurnierplanPublicSourceSelfChecks();
  const meinTurnierplanSync = runMeinTurnierplanSyncSelfChecks();
  const meinTurnierplanSyncRpc = runMeinTurnierplanSyncRpcSelfChecks();
  const transactionRollbackCheck = runMeinTurnierplanTransactionRollbackCheck();
  const idempotencyCheck = runMeinTurnierplanIdempotencyCheck();
  const manualOverrideCheck = runMeinTurnierplanManualOverrideCheck();
  const existingManualGroupsCheck = runMeinTurnierplanExistingManualGroupsCheck();
  const participantCountChecks = runMeinTurnierplanParticipantCountChecks();
  const combinedParticipantListChecks = runTournamentParticipantsListChecks();
  const participantLogoManagementChecks = runTournamentParticipantLogoManagementChecks();
  const clubLogoStorageUploadChecks = runTournamentParticipantLogoManagementChecks();
  const livePageChecks = runLivePageSelfChecks();
  const matchCenterDesignChecks = runMatchCenterDesignChecks();
  const publicTeamLabelChecks = runPublicTeamLabelChecks();
  const liveMatchLayoutChecks = runLiveMatchLayoutChecks();
  const tournamentStatusCapacityChecks = runTournamentStatusCapacityChecks();
  const siteUrlAndCspChecks = runSiteUrlAndCspChecks();
  const authLoginValidationChecks = runAuthLoginValidationChecks();
  const authCallbackChecks = runAuthCallbackChecks();
  const clubProfileSecurityChecks = runClubProfileSecurityChecks();
  const duplicateApplicationChecks = runDuplicateApplicationChecks();
  const guestApplicationFieldsChecks = runGuestApplicationFieldsChecks();
  const optionalApplicationFieldsChecks = runOptionalApplicationFieldsChecks();
  const cancellationRequestsChecks = runCancellationRequestsChecks();
  const cancellationEmailHotfixChecks = runCancellationEmailHotfixChecks();
  const teamOperationsP2Checks = runTeamOperationsP2Checks();
  const rbacChecks = runRbacChecks();
  const rbacDomainRlsChecks = runRbacDomainRlsChecks();
  const rbacSecurityDefinerChecks = runRbacSecurityDefinerChecks();
  const userManagementChecks = runUserManagementChecks();
  const invitationChecks = runInvitationChecks();
  const invitationAuthErrorChecks = runInvitationAuthErrorChecks();
  const invitationServiceGrantsChecks = runInvitationServiceGrantsChecks();
  const invitationAcceptanceChecks = runInvitationAcceptanceChecks();
  const invitationAcceptanceRpcChecks = runInvitationAcceptanceRpcChecks();
  const userDeleteChecks = runUserDeleteChecks();
  const paymentStatusChecks = runPaymentStatusChecks();
  const communicationChecks = runCommunicationChecks();
  const communicationRecipientPickerChecks = runCommunicationRecipientPickerChecks();
  const communicationRecipientDedupChecks = runCommunicationRecipientDedupChecks();
  const communicationTeamDirectoryChecks = runCommunicationTeamDirectoryChecks();
  const communicationSendOutcomeChecks = runCommunicationSendOutcomeChecks();
  const communicationListChecks = runCommunicationListChecks();
  const communicationTableGrantChecks = runCommunicationTableGrantChecks();
  const communicationInterruptedChecks = runCommunicationInterruptedChecks();
  const helpChatChecks = runHelpChatChecks();
  const communicationReceiptChecks = runCommunicationReceiptChecks();
  const applicationCapacityDisplayChecks = runApplicationCapacityDisplayChecks();
  const publicApplicationStatusDisplayChecks = runPublicApplicationStatusDisplayChecks();
  const publicTournamentAnonVisibilityChecks = runPublicTournamentAnonVisibilityChecks();
  const newsSelfChecks = runNewsSelfChecks();
  const adminScheduleParticipantChecks = runAdminScheduleParticipantChecks();
  const statusEmailIdempotencyChecks = runStatusEmailIdempotencySelfChecks();
  const statusEmailConcurrencyChecks = runStatusEmailConcurrencySelfChecks();
  const tournamentHubEmailDesignChecks = runTournamentHubEmailDesignChecks();
  const teamDirectoryChecks = runTeamDirectoryChecks();
  console.log(`schedule-checks: ${schedule}`);
  console.log(`application-window-checks: ${applicationWindow}`);
  console.log(`mein-turnierplan-checks: ${meinTurnierplan}`);
  console.log(`mein-turnierplan-import-checks: ${meinTurnierplanImport}`);
  console.log(`mein-turnierplan-normalize-checks: ${meinTurnierplanNormalize}`);
  console.log(`mein-turnierplan-live-render-checks: ${meinTurnierplanLiveRender}`);
  console.log(`mein-turnierplan-public-source-checks: ${meinTurnierplanPublicSource}`);
  console.log(`mein-turnierplan-sync-checks: ${meinTurnierplanSync}`);
  console.log(`mein-turnierplan-sync-rpc-checks: ${meinTurnierplanSyncRpc}`);
  console.log(`transaction-rollback-check: ${transactionRollbackCheck}`);
  console.log(`idempotency-check: ${idempotencyCheck}`);
  console.log(`manual-override-check: ${manualOverrideCheck}`);
  console.log(`existing-manual-groups-check: ${existingManualGroupsCheck}`);
  console.log(`mein-turnierplan-participant-count-checks: ${participantCountChecks}`);
  console.log(`combined-participant-list-checks: ${combinedParticipantListChecks}`);
  console.log(`participant-logo-management-checks: ${participantLogoManagementChecks}`);
  console.log(`club-logo-storage-upload-checks: ${clubLogoStorageUploadChecks}`);
  console.log(`live-page-checks: ${livePageChecks}`);
  console.log(`match-center-design-checks: ${matchCenterDesignChecks}`);
  console.log(`public-team-label-checks: ${publicTeamLabelChecks}`);
  console.log(`live-match-layout-checks: ${liveMatchLayoutChecks}`);
  console.log(`tournament-status-capacity-checks: ${tournamentStatusCapacityChecks}`);
  console.log(`site-url-csp-checks: ${siteUrlAndCspChecks}`);
  console.log(`auth-login-validation-checks: ${authLoginValidationChecks}`);
  console.log(`auth-callback-checks: ${authCallbackChecks}`);
  console.log(`club-profile-security-checks: ${clubProfileSecurityChecks}`);
  console.log(`duplicate-application-checks: ${duplicateApplicationChecks}`);
  console.log(`guest-application-fields-checks: ${guestApplicationFieldsChecks}`);
  console.log(`optional-application-fields-checks: ${optionalApplicationFieldsChecks}`);
  console.log(`cancellation-requests-checks: ${cancellationRequestsChecks}`);
  console.log(`cancellation-email-hotfix-checks: ${cancellationEmailHotfixChecks}`);
  console.log(`team-operations-p2-checks: ${teamOperationsP2Checks}`);
  console.log(`rbac-checks: ${rbacChecks}`);
  console.log(`rbac-domain-rls-checks: ${rbacDomainRlsChecks}`);
  console.log(`rbac-security-definer-checks: ${rbacSecurityDefinerChecks}`);
  console.log(`user-management-checks: ${userManagementChecks}`);
  console.log(`invitation-checks: ${invitationChecks}`);
  console.log(`invitation-auth-error-checks: ${invitationAuthErrorChecks}`);
  console.log(`invitation-service-grants-checks: ${invitationServiceGrantsChecks}`);
  console.log(`invitation-acceptance-checks: ${invitationAcceptanceChecks}`);
  console.log(`invitation-acceptance-rpc-checks: ${invitationAcceptanceRpcChecks}`);
  console.log(`user-delete-checks: ${userDeleteChecks}`);
  console.log(`payment-status-checks: ${paymentStatusChecks}`);
  console.log(`communication-checks: ${communicationChecks}`);
  console.log(`communication-recipient-picker-checks: ${communicationRecipientPickerChecks}`);
  console.log(`communication-recipient-dedup-checks: ${communicationRecipientDedupChecks}`);
  console.log(`communication-team-directory-checks: ${communicationTeamDirectoryChecks}`);
  console.log(`communication-send-outcome-checks: ${communicationSendOutcomeChecks}`);
  console.log(`communication-list-checks: ${communicationListChecks}`);
  console.log(`communication-table-grant-checks: ${communicationTableGrantChecks}`);
  console.log(`communication-interrupted-checks: ${communicationInterruptedChecks}`);
  console.log(`help-chat-checks: ${helpChatChecks}`);
  console.log(`communication-receipt-checks: ${communicationReceiptChecks}`);
  console.log(`application-capacity-display-checks: ${applicationCapacityDisplayChecks}`);
  console.log(`public-application-status-display-checks: ${publicApplicationStatusDisplayChecks}`);
  console.log(`public-tournament-anon-visibility-checks: ${publicTournamentAnonVisibilityChecks}`);
  console.log(`news-self-checks: ${newsSelfChecks}`);
  console.log(`admin-schedule-participant-checks: ${adminScheduleParticipantChecks}`);
  console.log(`status-email-idempotency-checks: ${statusEmailIdempotencyChecks}`);
  console.log(`status-email-concurrency-checks: ${statusEmailConcurrencyChecks}`);
  console.log(`tournament-hub-email-design-checks: ${tournamentHubEmailDesignChecks}`);
  console.log(`team-directory-checks: ${teamDirectoryChecks}`);
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
